/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects */
        get: {
            parameters: {
                query: {
                    workspace_id: components["parameters"]["WorkspaceId"];
                    page?: components["parameters"]["Page"];
                    page_size?: components["parameters"]["PageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ProjectList"];
            };
        };
        put?: never;
        /** Create a project */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateProject"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /** Get a project */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: components["parameters"]["ProjectId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Project */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** Permanently delete a project and its private objects */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: components["parameters"]["ProjectId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a signed source upload */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateUpload"];
                };
            };
            responses: {
                /** @description Signed upload created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{documentId}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate a completed upload */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    documentId: components["parameters"]["DocumentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Validated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/estimates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extract or OCR a source and calculate exact source-word credits */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EstimateRequest"];
                };
            };
            responses: {
                /** @description Estimate */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Estimate"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/translations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reserve credits and start a durable translation workflow */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "Idempotency-Key"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StartTranslation"];
                };
            };
            responses: {
                /** @description Started */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                402: components["responses"]["Error"];
                409: components["responses"]["Error"];
                429: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/translations/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Cancel or retry a translation job */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: components["parameters"]["JobId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        action: "cancel" | "retry_failed";
                    };
                };
            };
            responses: {
                /** @description Action accepted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve job progress, warnings, and errors */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: components["parameters"]["JobId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Job progress */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["JobProgress"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/segments/{segmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit source OCR or translated text */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    segmentId: components["parameters"]["SegmentId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EditSegment"];
                };
            };
            responses: {
                /** @description Saved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/segments/{segmentId}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve revision history */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    segmentId: components["parameters"]["SegmentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Revision list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit, request changes, or approve */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReviewAction"];
                };
            };
            responses: {
                /** @description Review state changed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                409: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate DOCX, PDF, or text output */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ExportRequest"];
                };
            };
            responses: {
                /** @description Export ready */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exports/{exportId}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download a private export */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    exportId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Export bytes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List personal and organization workspaces */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Workspace list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create an organization workspace */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspaceId}/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invite a member */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: components["parameters"]["WorkspaceIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Invitation created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspaceId}/glossary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List glossary terms */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: components["parameters"]["WorkspaceIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Term list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Add a glossary term */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: components["parameters"]["WorkspaceIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/credits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve balance and ledger */
        get: {
            parameters: {
                query: {
                    workspace_id: components["parameters"]["WorkspaceId"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Credit account and ledger */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve global-learning consent */
        get: {
            parameters: {
                query: {
                    workspace_id: components["parameters"]["WorkspaceId"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Consent */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Update global-learning consent */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        WorkspaceRole: "owner" | "admin" | "translator" | "reviewer";
        /** @enum {string} */
        LanguageDirection: "en-ar" | "ar-en";
        /** @enum {string} */
        ProjectState: "draft" | "estimating" | "ready" | "translating" | "review" | "approved" | "failed" | "cancelled";
        /** @enum {string} */
        JobStage: "queued" | "validating" | "extracting" | "ocr_review" | "reserving_credits" | "retrieving_context" | "translating" | "quality_check" | "reconstructing" | "completed" | "failed" | "cancelled";
        Project: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            workspaceId: string;
            title: string;
            direction: components["schemas"]["LanguageDirection"];
            state: components["schemas"]["ProjectState"];
            sourceWordCount: number;
        };
        ProjectEnvelope: {
            data?: components["schemas"]["Project"];
        };
        CreateProject: {
            /** Format: uuid */
            workspaceId: string;
            title: string;
            direction: components["schemas"]["LanguageDirection"];
        };
        CreateUpload: {
            /** Format: uuid */
            workspaceId: string;
            /** Format: uuid */
            projectId: string;
            fileName: string;
            mimeType: string;
            size: number;
        };
        EstimateRequest: {
            /** Format: uuid */
            workspaceId: string;
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            documentId?: string;
            text?: string;
            direction: components["schemas"]["LanguageDirection"];
        };
        Estimate: {
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            documentId: string;
            /** Format: uuid */
            versionId: string;
            sourceWordCount: number;
            pageCount: number;
            requiresOcrReview: boolean;
        };
        StartTranslation: {
            /** Format: uuid */
            workspaceId: string;
            /** Format: uuid */
            projectId: string;
        };
        JobProgress: {
            /** Format: uuid */
            id: string;
            stage: components["schemas"]["JobStage"];
            progress: number;
            completedSegments: number;
            totalSegments: number;
            errorCode?: string | null;
            errorMessage?: string | null;
        };
        EditSegment: {
            sourceText?: string;
            translatedText?: string;
            reason?: string;
        };
        ReviewAction: {
            /** Format: uuid */
            workspaceId: string;
            /** Format: uuid */
            projectId: string;
            /** @enum {string} */
            action: "submit" | "request_changes" | "approve";
            /** @default false */
            ownerOverride: boolean;
            reason?: string;
        };
        ExportRequest: {
            /** Format: uuid */
            workspaceId: string;
            /** Format: uuid */
            projectId: string;
            /** @enum {string} */
            format: "docx" | "pdf" | "txt";
        };
        ErrorEnvelope: {
            error: {
                code: string;
                message: string;
            };
        };
    };
    responses: {
        /** @description Request error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Project list */
        ProjectList: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: {
        WorkspaceId: string;
        WorkspaceIdPath: string;
        ProjectId: string;
        DocumentId: string;
        JobId: string;
        SegmentId: string;
        Page: number;
        PageSize: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
