"use client";

import { useState } from "react";
import { Database, LockKeyhole, ShieldCheck } from "lucide-react";
import { Card } from "@/components/ui/card";

export function PrivacySettings({ workspaceId, initialConsent }: { workspaceId?: string; initialConsent: boolean }) {
  const [consent, setConsent] = useState(initialConsent);
  const [busy, setBusy] = useState(false);
  const [status, setStatus] = useState<string | null>(null);
  async function updateConsent(next: boolean) {
    if (!workspaceId) return; setBusy(true); setStatus(null);
    const response = await fetch("/api/v1/consent", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ workspaceId, globalLearning: next }) });
    setBusy(false); if (response.ok) { setConsent(next); setStatus("Privacy preference saved."); } else setStatus("The preference could not be saved.");
  }
  return <div><div className="max-w-3xl"><p className="text-sm font-semibold text-[var(--accent)]">Data controls</p><h1 className="mt-2 text-3xl font-bold tracking-[-0.035em] sm:text-4xl">Privacy & learning</h1><p className="mt-3 leading-7 text-[var(--muted)]">Private learning stays on for your workspace. Global learning is separate, off by default, and requires explicit consent.</p></div><div className="mt-8 grid gap-4 lg:grid-cols-2"><Card className="p-6"><span className="grid size-11 place-items-center rounded-xl bg-[var(--accent-soft)] text-[var(--accent)]"><LockKeyhole aria-hidden="true" size={20} /></span><h2 className="mt-5 font-bold">Private workspace memory</h2><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Approved corrections and terminology can improve later translations in this workspace. They never cross workspace boundaries.</p><p className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[var(--success)]"><ShieldCheck aria-hidden="true" size={17} /> Enabled</p></Card><Card className="p-6"><div className="flex items-start justify-between gap-5"><span className="grid size-11 place-items-center rounded-xl bg-[var(--subtle)] text-[var(--muted)]"><Database aria-hidden="true" size={20} /></span><label className="relative inline-flex min-h-11 items-center"><input type="checkbox" className="peer sr-only" checked={consent} disabled={!workspaceId || busy} onChange={(event) => updateConsent(event.target.checked)} /><span className="h-7 w-12 rounded-full bg-[var(--border)] transition-colors peer-checked:bg-[var(--accent)] peer-focus-visible:outline peer-focus-visible:outline-3 peer-focus-visible:outline-[var(--ring)] after:absolute after:start-1 after:top-1/2 after:size-5 after:-translate-y-1/2 after:rounded-full after:bg-white after:transition-transform peer-checked:after:translate-x-5 rtl:peer-checked:after:-translate-x-5" /><span className="sr-only">Allow de-identified approved segments for global learning</span></label></div><h2 className="mt-5 font-bold">Global learning contribution</h2><p className="mt-3 text-sm leading-6 text-[var(--muted)]">When enabled, only de-identified, manually approved segment pairs may enter a global candidate corpus. Raw documents are not automatically submitted.</p><p className="mt-5 text-sm font-bold text-[var(--muted)]">Currently {consent ? "allowed" : "off"}</p>{status && <p aria-live="polite" className="mt-2 text-sm text-[var(--muted)]">{status}</p>}</Card></div><Card className="mt-6 p-6"><h2 className="font-bold">Document retention</h2><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Source files, translations, and exports remain stored until you delete the project. Deleting a project schedules its private Storage objects and database content for removal.</p></Card></div>;
}
